const auth = require('../controller/auth-controller')
const post = require('../controller/upload-controller')
const upload = require('../controller/upload')
const posts = require('../controller/posts')
//const trends = require('../controller/trends-controller')
module.exports = (app) => {
  app.post('/register', auth.register)
  app.post('/login', auth.login)
  app.post('/search', auth.search)
  app.post('/follow', auth.follow)
  app.post('/all', auth.allusers)
  app.post('/upload', upload.uploadSingle, post.upload)
  app.post('/get', post.get)
  app.post('/newlikes', posts.like)
  app.post('/newcomment', posts.comment)
  app.post('/getpopular', post.getpopular)
  app.post('/getuser', auth.getuser)
  //app.get('/trends', trends.trends)
  //app.get('/verify', auth.verify)
}